"""empty message

Revision ID: f1511d1060a7
Revises: ffdc0a98111c
Create Date: 2022-02-15 12:46:44.095625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1511d1060a7'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('init_balance', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('curr_balance', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'curr_balance')
    op.drop_column('users', 'init_balance')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
